remote_theme: pages-themes/architect@v0.2.0

title: "Moja Strona GitHub Pages"
description: "Opis mojej strony GitHub Pages"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme 

permalink: /:categories/:title/
